version: '3.5'

services:
  # WordPress
  wordpress:
    container_name: wordpress
    image: wordpress:latest
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - 8000:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_NAME: db
      WORDPRESS_DB_USER: dbuser
      WORDPRESS_DB_PASSWORD: dbpassword
      WORDPRESS_TABLE_PREFIX: wp_
    networks:
      web:
        aliases:
          - wordpress

  # Database
  database:
    container_name: database
    image: mysql:5.7
    volumes:
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=securerootpassword
      - MYSQL_DATABASE=db
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpassword
    networks:
      web:
        aliases:
          - database

  # phpMyAdmin
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    ports:
      - 8080:80
    restart: always
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: securerootpassword 
    networks:
      web:
        aliases:
          - phpmyadmin

networks:
  web:
    name: web-network